# -*- coding: utf-8 -*-

"""
calculatormharis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OperationTypeEnum(object):

    """Implementation of the 'Operation Type' enum.

    Possible operations are add, subtract, multiply, divide.

    Attributes:
        ADD: TODO: type description here.
        SUBTRACT: TODO: type description here.

    """

    ADD = 'SUM'

    SUBTRACT = 'SUBTRACT'
